---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: configuration
- type: directory
  path: content/impact
  label: Impact
  create: all
  match: "**/*"
- type: directory
  path: content/how-to-engage
  label: How To Engage
  create: all
  match: "**/*"
- type: directory
  path: content/pillars
  label: Pillars
  create: all
  match: "**/*"
- type: directory
  path: content/partners
  label: Partners
  create: all
  match: "**/*"
- type: directory
  path: content/business-case
  label: Business Case
  create: all
  match: "**/*"
- type: directory
  path: content/how-it-works
  label: How it works (timeline)
  create: all
  match: "**/*"
upload_dir: static
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
